# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3,4])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3], [4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2],[2,3]],[[4,5],[6,7]],[[6,7],[8,9]]])
a3

array([[[1, 2],
        [2, 3]],

       [[4, 5],
        [6, 7]],

       [[6, 7],
        [8, 9]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.dtype

dtype('int32')

In [4]:
a1.shape

(4,)

In [5]:
a1.size

4

In [6]:
# Attributes of 2-dimensional array
a2.dtype

dtype('int32')

In [7]:
a2.size

6

In [8]:
a2.shape

(2, 3)

In [9]:
# Attributes of 3-dimensional array
a3.dtype

dtype('int32')

In [10]:
a3.size

12

In [11]:
a3.shape

(3, 2, 2)

In [12]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
# now I will create the dataframe according to a1 array
df1 = pd.DataFrame(a1, columns=["number"])
df1

number
0       1
1       2
2       3
3       4

In [13]:
# now I will create dataframe for a2
df2 = pd.DataFrame(a2, columns=['number1','number2','number3'])
df2

number1  number2  number3
0        1        2        3
1        4        5        6

In [14]:
# Create an array of shape (10, 2) with only ones
arrOnes = np.ones((10,2))
arrOnes

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
# Create an array of shape (7, 2, 3) of only zeros
arrZeros =  np.zeros((7,2,3))
arrZeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [16]:
# Create an array within a range of 0 and 100 with step 3
arrRange = np.arange(0, 100, 3)
arrRange

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [17]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arrRandInt = np.random.randint(0, 10, (7,2))
arrRandInt

array([[4, 5],
       [4, 1],
       [9, 6],
       [4, 4],
       [8, 3],
       [9, 0],
       [6, 9]])

In [18]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arrRandFloat = np.random.uniform(low=0.0, high=1.0, size=(3,5))
arrRandFloat

array([[0.17104266, 0.46600605, 0.47766767, 0.06872127, 0.85218029],
       [0.27859932, 0.30653565, 0.225324  , 0.56859672, 0.19754031],
       [0.53153407, 0.29763974, 0.59827157, 0.95731747, 0.30586897]])

In [19]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arrRandSeeded = np.random.randint(0, 10, size=(4,6))
arrRandSeeded

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

The numbers will always be the same no matter how many times I re run the cell. This is because I already set the seed of the random generator to a specific setting number.

In [20]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arrRandUnique = np.random.randint(1,10,(3,7))
arrRandUnique

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [21]:
# Find the unique numbers in the array you just created
np.unique(arrRandUnique)

array([1, 2, 3, 4, 5, 7, 9])

In [22]:
# Find the 0'th index of the latest array you created
arrRandUnique[0]

array([9, 1, 3, 7, 4, 9, 3])

In [23]:
# Get the first 2 rows of latest array you created
arrRandUnique[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [24]:
# Get the first 2 values of the first 2 rows of the latest array
arrRandUnique[:2,:2]

array([[9, 1],
       [5, 3]])

In [25]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arrRandInt2 = np.random.randint(0, 10, (3, 5))
arrOnes2 = np.ones((3, 5))
arrRandInt2

array([[6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1]])

In [26]:
# Add the two arrays together
arrRandInt2 + arrOnes2

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [27]:
# Create another array of ones of shape (5, 3)
arrOnes3 =  np.ones((5,3))
arrOnes3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
# Try add the array of ones and the other most recent array together
(arrRandInt2 + arrOnes2) + np.reshape(arrOnes3,(3,5))

array([[ 8.,  9.,  4.,  2.,  5.],
       [ 3.,  9.,  5.,  3.,  7.],
       [ 7., 11.,  5.,  7.,  3.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?
Well the numpy broadcast failed to allow the arithmetic operations. Broadcast here means the ability to perform arithmetic operations such as sum by numpy
Solution: I need to reshape the most recent array or the ones to be as the same shape as the other array.

In [29]:
# Create another array of ones of shape (3, 5)
arrOnes2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
# Subtract the new array of ones from the other most recent array
arrLatest = (arrRandInt2 + arrOnes2) + np.reshape(arrOnes3,(3,5)) - arrOnes2
arrLatest

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [31]:
# Multiply the ones array with the latest array
arrLatest = arrOnes2 * arrLatest
arrLatest

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [32]:
# Take the latest array to the power of 2 using '**'
arrLatest2 = arrLatest**2
arrLatest2

array([[ 49.,  64.,   9.,   1.,  16.],
       [  4.,  64.,  16.,   4.,  36.],
       [ 36., 100.,  16.,  36.,   4.]])

In [33]:
# Do the same thing with np.square()
np.square(arrLatest)

array([[ 49.,  64.,   9.,   1.,  16.],
       [  4.,  64.,  16.,   4.,  36.],
       [ 36., 100.,  16.,  36.,   4.]])

In [34]:
# Find the mean of the latest array using np.mean()
np.mean(arrLatest2)

30.333333333333332

In [35]:
# Find the maximum of the latest array using np.max()
np.max(arrLatest2)

100.0

In [36]:
# Find the minimum of the latest array using np.min()
np.min(arrLatest2)

1.0

In [37]:
# Find the standard deviation of the latest array
np.std(arrLatest2)

27.78168861358543

In [38]:
# Find the variance of the latest array
np.var(arrLatest2)

771.8222222222224

In [39]:
# Reshape the latest array to (3, 5, 1)
arrLatest2 = np.reshape(arrLatest2, (3,5,1))
arrLatest2

array([[[ 49.],
        [ 64.],
        [  9.],
        [  1.],
        [ 16.]],

       [[  4.],
        [ 64.],
        [ 16.],
        [  4.],
        [ 36.]],

       [[ 36.],
        [100.],
        [ 16.],
        [ 36.],
        [  4.]]])

In [40]:
# Transpose the latest array
np.transpose(arrLatest2)

array([[[ 49.,   4.,  36.],
        [ 64.,  64., 100.],
        [  9.,  16.,  16.],
        [  1.,   4.,  36.],
        [ 16.,  36.,   4.]]])

In [41]:
(np.transpose(arrLatest2)).shape

(1, 5, 3)

What does the transpose do?

Answer: transpose change the column to be the row of the matrix. Thus change the shape of the matrix.

In the case above the original matrix has shape of (3,5,1) while after transpose the shape changes to (1,5,3)

In [42]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arrRandInt3 = np.random.randint(0, 10, (3,3))
arrRandInt4 = np.random.randint(0, 10, (3,2))
arrRandInt3

array([[9, 1, 9],
       [3, 7, 6],
       [8, 7, 4]])

In [43]:
arrRandInt4

array([[1, 4],
       [7, 9],
       [8, 8]])

In [44]:
# Perform a dot product on the two newest arrays you created
np.dot(arrRandInt3, arrRandInt4)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [45]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arrRandInt5 = np.random.randint(0,10,(4,3))
arrRandInt6 = np.random.randint(0,10,(4,3))


In [46]:
# Perform a dot product on the two newest arrays you created
np.dot(arrRandInt5, np.reshape(arrRandInt6,(3,4)))

array([[ 96, 114,  70,  48],
       [ 58,  63,  88, 114],
       [ 72,  77,  86, 105],
       [ 58,  77,  58,  42]])

It doesn't work. How would you fix it?

I need to reshape one of the matrix (the later or the former in the dot product function does not matter) to (3,4)

In [47]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(arrRandInt5, np.transpose(arrRandInt6))

array([[ 24, 102,  96,   8],
       [ 16, 114, 106,  63],
       [ 22, 123, 114,  56],
       [  8,  60,  58,   7]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

The shape of the array that allowed to use the dot product operations must have corresponding inner shape similar like (2, 1) then the corresponding matrix must be (1, 2)

This is because the dot product will multiply and sum the row with columns from each matrix 

In [63]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arrRandInt7 = np.random.randint(0,10,(3,2))
arrRandInt8 = np.random.randint(0,10,(3,2))

In [64]:
# Compare the two arrays with '>'
arrRandInt7 > arrRandInt8

array([[ True, False],
       [ True, False],
       [False,  True]])

What happens when you compare the arrays with `>`?

Answer: each element in both matrix which resides in the same column and row will be compared. If the arrRandInt7 element at row i and column j is higher to arrRandInt8 element at row i and column j then it will returns true and vice versa. 

In [65]:
# Compare the two arrays with '>='
arrRandInt7 >= arrRandInt8

array([[ True, False],
       [ True, False],
       [False,  True]])

In [66]:
# Find which elements of the first array are greater than 7
arrRandInt7 > 7

array([[False, False],
       [False, False],
       [False, False]])

In [67]:
# Which parts of each array are equal? (try using '==')
arrRandInt7 == arrRandInt8

array([[False, False],
       [False, False],
       [False, False]])

In [68]:
# Sort one of the arrays you just created in ascending order
np.sort(arrRandInt8)

array([[2, 5],
       [1, 9],
       [4, 8]])

In [70]:
# Sort the indexes of one of the arrays you just created
np.argsort(arrRandInt8)

array([[0, 1],
       [0, 1],
       [1, 0]], dtype=int64)

In [71]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(arrRandInt8)

3

In [72]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arrRandInt8)

2

In [73]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arrRandInt8, 1)

array([1, 1, 0], dtype=int64)

In [74]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arrRandInt8, 0)

array([1, 2], dtype=int64)

In [76]:
# Create an array of normally distributed random numbers
np.random.normal(0.0, 1.0,(4,3))

array([[ 0.3145129 ,  1.37186213,  0.17555329],
       [-0.30928855,  0.6731255 , -0.25663018],
       [-0.36782572,  1.27373362, -0.29195267],
       [-2.65517605,  0.34551794, -0.39551645]])

In [77]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.