THIS IS THE PYTHON NUMPY FILE FOR UDEMY

In [1]:
# IMPORTING NUMPY TO EXPLORE ITS FUNCTION
import numpy as np

In [2]:
# creating first nd array (n dimensional array)
a1 = np.array([1,2,3])
# print the a1 to see the array:
a1

array([1, 2, 3])

In [3]:
# see the type of the array (n dimeensional array) a1
type(a1)

numpy.ndarray

In [4]:
# now let's try to make multi dimensional array (2 dimensional and 3 dimenasional)
a2 = np.array([[1, 2.0, 3.3],[4, 5, 6.5]])
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])
# lets tru to print a2 and a3
print('a2 = ')
a2

a2 = 


array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [5]:
print('a3= ')
a3


a3= 


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
# let's see the shape of each matix
a1.shape

(3,)

In [7]:
print('a2 shape=')
a2.shape

a2 shape=


(2, 3)

In [8]:
print('a3 shape=')
a3.shape

a3 shape=


(2, 3, 3)

In [9]:
# now we see the dimenstion of the matrix
a1.ndim

1

In [10]:
# now we seee multiple dimension of each 3 matrices
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
# next is thee size or the number of character inside the matrix
a1.size, a2.size, a3.size

(3, 6, 18)

In [12]:
# now combining panda to make data array from a matrix
# make sure the matrix has d nsim ( in this case the qualified is a2)
import pandas as pd 
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [13]:
# we can also see the dtype of the array
a2.dtype

dtype('float64')

In [14]:
a1.dtype

dtype('int32')

In [15]:
# creating matrix which all the value is 1 which all int (I need to specify this since the default value is float)
ones = np.ones((2,3), int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [16]:
ones.dtype

dtype('int32')

In [17]:
# create 2 by 3 matrix all zero in float datatype
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
zeros.dtype

dtype('float64')

In [19]:
# make an arranged matrix within 0 to 9
rangeArray = np.arange(0, 10, 2)
rangeArray

array([0, 2, 4, 6, 8])

In [20]:
# making random matrix size 3,5
randomArray = np.random.randint(0, 10, size=(3,5))
randomArray

array([[2, 6, 7, 5, 4],
       [6, 8, 6, 3, 2],
       [1, 8, 9, 2, 6]])

In [21]:
# making a random float maatrix size 5,3
randomArray2 = np.random.random((5,3))
randomArray2

array([[0.0366967 , 0.60128343, 0.67245414],
       [0.18424415, 0.67465467, 0.88193996],
       [0.50495806, 0.91474299, 0.80973118],
       [0.34041005, 0.00597151, 0.05160973],
       [0.54013349, 0.57683634, 0.0701356 ]])

In [22]:
randomArray3 = np.random.rand(5,3)
randomArray3

array([[0.15491003, 0.29405039, 0.20786883],
       [0.38176403, 0.23820926, 0.23965593],
       [0.92700679, 0.69254153, 0.00190973],
       [0.68955692, 0.99818403, 0.96606962],
       [0.69869976, 0.52394052, 0.65596017]])

In [23]:
matrixTest1 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[20,21,22],[23,24,25],[26,27,28]]])
matrixTest1

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]]])

In [24]:
matrixTest1.shape

(3, 3, 3)

In [25]:
matrixCompare1 = np.array([[[1,2,3],
                            [4,5,6],
                            [7,8,9]],
                            [[10,11,12],
                            [13,14,15],
                            [16,17,18]]])
matrixCompare1

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [26]:
matrixCompare1.shape

(2, 3, 3)

In [27]:
matrixCompare1.size

18

In [28]:
matrixCompare2 = np.array([[[1,2,3],[4,5,6]],
                            [[7,8,9],[10,11,12]],
                            [[13,14,15],[16,17,18]]])
matrixCompare2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [29]:
matrixCompare2.shape

(3, 2, 3)

In [30]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[0, 8, 8, 7, 1],
         [9, 8, 8, 6, 5],
         [5, 2, 3, 1, 1],
         [8, 4, 4, 2, 8]],

        [[9, 9, 3, 2, 7],
         [5, 2, 2, 9, 3],
         [9, 0, 5, 4, 8],
         [5, 3, 8, 5, 1]],

        [[1, 9, 7, 7, 7],
         [6, 5, 6, 9, 4],
         [4, 5, 5, 6, 8],
         [0, 0, 7, 4, 1]]],


       [[[3, 1, 0, 1, 3],
         [9, 9, 1, 8, 2],
         [1, 1, 4, 8, 4],
         [4, 2, 5, 1, 7]],

        [[0, 2, 8, 2, 4],
         [3, 6, 1, 1, 3],
         [3, 4, 0, 9, 7],
         [6, 8, 2, 5, 1]],

        [[0, 9, 2, 6, 8],
         [6, 6, 6, 5, 3],
         [7, 0, 2, 6, 8],
         [3, 9, 3, 7, 2]]]])

In [31]:
a4.shape

(2, 3, 4, 5)

In [32]:
a4[:,:,:,:4]

array([[[[0, 8, 8, 7],
         [9, 8, 8, 6],
         [5, 2, 3, 1],
         [8, 4, 4, 2]],

        [[9, 9, 3, 2],
         [5, 2, 2, 9],
         [9, 0, 5, 4],
         [5, 3, 8, 5]],

        [[1, 9, 7, 7],
         [6, 5, 6, 9],
         [4, 5, 5, 6],
         [0, 0, 7, 4]]],


       [[[3, 1, 0, 1],
         [9, 9, 1, 8],
         [1, 1, 4, 8],
         [4, 2, 5, 1]],

        [[0, 2, 8, 2],
         [3, 6, 1, 1],
         [3, 4, 0, 9],
         [6, 8, 2, 5]],

        [[0, 9, 2, 6],
         [6, 6, 6, 5],
         [7, 0, 2, 6],
         [3, 9, 3, 7]]]])

In [33]:
a4[:,:,:1,:]

array([[[[0, 8, 8, 7, 1]],

        [[9, 9, 3, 2, 7]],

        [[1, 9, 7, 7, 7]]],


       [[[3, 1, 0, 1, 3]],

        [[0, 2, 8, 2, 4]],

        [[0, 9, 2, 6, 8]]]])

In [34]:
seed = np.random.seed(35)
seedTrial1 = np.random.randint(10, size=(4,5))
seedTrial1

array([[9, 7, 1, 0, 9],
       [8, 8, 8, 9, 7],
       [7, 8, 0, 9, 2],
       [5, 3, 3, 3, 9]])

In [35]:
np.unique(seedTrial1)

array([0, 1, 2, 3, 5, 7, 8, 9])

This is the Numpy Manipulating Aray

In [36]:
# Aritmatic Operations.
a1

array([1, 2, 3])

In [37]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [38]:
a1 + ones

array([2., 3., 4.])

In [39]:
a1 * ones

array([1., 2., 3.])

In [40]:
a1 - ones

array([0., 1., 2.])

In [41]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [42]:
a1*a2
## this is the multiplication between two matrices wich different in shape

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [43]:
a2.shape

(2, 3)

In [44]:
a1.shape

(3,)

In [45]:
# now the problem is when the shape of the matrices are not compatible.
a3.shape

(2, 3, 3)

In [46]:
a2.shape

(2, 3)

In [47]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [48]:
a2/a1 #division which uses the correct broadcast

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [49]:
a1/a2 # this is the division is also can be done from smaller vector to bigger vector

array([[1.        , 1.        , 0.90909091],
       [0.25      , 0.4       , 0.46153846]])

In [50]:
# now we try to quadratic operation
a2**2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [51]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [52]:
# AGGREGATION 
np.sum(a1)

6

In [53]:
np.std(a3)

5.188127472091127

In [54]:
np.var(a3)

26.916666666666668

In [55]:
np.sqrt(np.var(a3)) # this is supposed to be the same as numpy std method!

5.188127472091127