THIS IS THE PYTHON NUMPY FILE FOR UDEMY

In [1]:
# IMPORTING NUMPY TO EXPLORE ITS FUNCTION
import numpy as np

In [2]:
# creating first nd array (n dimensional array)
a1 = np.array([1,2,3])
# print the a1 to see the array:
a1

array([1, 2, 3])

In [3]:
# see the type of the array (n dimeensional array) a1
type(a1)

numpy.ndarray

In [5]:
# now let's try to make multi dimensional array (2 dimensional and 3 dimenasional)
a2 = np.array([[1, 2.0, 3.3],[4, 5, 6.5]])
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])
# lets tru to print a2 and a3
print('a2 = ')
a2

a2 = 


array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
print('a3= ')
a3


a3= 


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
# let's see the shape of each matix
a1.shape

(3,)

In [8]:
print('a2 shape=')
a2.shape

a2 shape=


(2, 3)

In [9]:
print('a3 shape=')
a3.shape

a3 shape=


(2, 3, 3)

In [12]:
# now we see the dimenstion of the matrix
a1.ndim

1

In [13]:
# now we seee multiple dimension of each 3 matrices
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
# next is thee size or the number of character inside the matrix
a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
# now combining panda to make data array from a matrix
# make sure the matrix has d nsim ( in this case the qualified is a2)
import pandas as pd 
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [17]:
# we can also see the dtype of the array
a2.dtype

dtype('float64')

In [18]:
a1.dtype

dtype('int64')

In [23]:
# creating matrix which all the value is 1 which all int (I need to specify this since the default value is float)
ones = np.ones((2,3), int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [24]:
ones.dtype

dtype('int64')

In [25]:
# create 2 by 3 matrix all zero in float datatype
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
zeros.dtype

dtype('float64')

In [27]:
# make an arranged matrix within 0 to 9
rangeArray = np.arange(0, 10, 2)
rangeArray

array([0, 2, 4, 6, 8])

In [28]:
# making random matrix size 3,5
randomArray = np.random.randint(0, 10, size=(3,5))
randomArray

array([[4, 7, 6, 2, 8],
       [1, 1, 8, 7, 4],
       [0, 3, 3, 2, 3]])

In [30]:
# making a random float maatrix size 5,3
randomArray2 = np.random.random((5,3))
randomArray2

array([[0.00831246, 0.03803703, 0.78068784],
       [0.68290836, 0.87115348, 0.35608096],
       [0.16476009, 0.21133289, 0.02316266],
       [0.68803071, 0.67448686, 0.58295763],
       [0.13143479, 0.95061956, 0.70837144]])

In [31]:
randomArray3 = np.random.rand(5,3)
randomArray3

array([[0.11186264, 0.88888195, 0.62140844],
       [0.49506951, 0.21348281, 0.41869628],
       [0.5396816 , 0.88415886, 0.90053335],
       [0.63882862, 0.130087  , 0.32336407],
       [0.2871319 , 0.02276992, 0.71660291]])

In [32]:
#pseudo-random numbers
np.random.seed()